# Regresión lineal con Scikit learn

In [15]:
#Importaremos las librerias correspondientes (RFE,SVR, Pandas y Numpy)

In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [ ]:
#Importamos el archivo para el cual queremos hallar la relación lineal

In [2]:
data=pd.read_csv("Advertising.csv")

In [17]:
#Creamos un arreglo con las variables predictoras

In [3]:
feature_cols=["TV","Radio","Newspaper"]

In [4]:
x=data[feature_cols]
y=data["Sales"]

In [21]:
#Seleccionaremos que variables incluir en el modelo

In [22]:
estimator=SVR(kernel="linear")
selector=RFE(estimator,2,step=1)
selector=selector.fit(x,y)

In [23]:
#Las variables true serán incluidas, mientras que false serán descartadas

In [19]:
selector.support_

array([ True,  True, False])

In [20]:
selector.ranking_

array([1, 1, 2])

In [24]:
#Importamos la libreria para implementar el modelo lineal

In [25]:
from sklearn.linear_model import LinearRegression

In [26]:
#Dejamos las variables predictoras

In [27]:
x_pred=x[["TV","Radio"]]

In [ ]:
#Aplicamos la regresión lineal

In [28]:
lm=LinearRegression()
lm.fit(x_pred,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [29]:
#Obtendremos los coeficientes del modelo

In [30]:
lm.intercept_

2.921099912405138

In [31]:
lm.coef_

array([0.04575482, 0.18799423])

In [32]:
#Calcularemos R2

In [33]:
lm.score(x_pred,y)

0.8971942610828956

# El modelo lineal sería:
### Sales= 2.921099912405138+0.04575482*TV+0.18799423*Radio